In [ ]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
np.set_printoptions(precision=5, suppress=True)

In [3]:
from quantum_masala.core import RealLattice, UPFv2Data, AtomBasis, Crystal
from quantum_masala.core.constants import angstrom, E_ryd, E_ryd_SI, eV

reallat = RealLattice.from_alat(5.1070, [0.5, 0.5, 0.5], [-0.5, 0.5, 0.5], [-0.5, -0.5, 0.5])

fe_oncv = UPFv2Data.from_file('fe', './fe/Fe_ONCV_PBE-1.2.upf')

fe_atoms = AtomBasis.from_cart(reallat, 'fe', 55.487, fe_oncv, [0., 0., 0.])

crystal = Crystal(reallat, [fe_atoms])

In [4]:
reallat = crystal.reallat
recilat = crystal.recilat

print(f"alat = {reallat.alat}")
print("Axes of real space in cartesian")
for i, ai in enumerate(reallat.axes_cart):
    print(f"a({i+1}) = {ai}")
print()
print("Axes of real space in alat")
for i, ai in enumerate(reallat.axes_alat):
    print(f"a({i+1}) = {ai}")
print('-'*40)
print()


print(f"tpiba = {recilat.tpiba}")
print("Axes of reciprocal space in tpiba")
for i, bi in enumerate(recilat.axes_tpiba):
    print(f"b({i+1}) = {bi}")
print()
print("Axes of reciprocal space in cart")
for i, bi in enumerate(recilat.axes_cart):
    print(f"b({i+1}) = {bi}")
print('-'*40)
print()

for sp in crystal.l_species:
    print(f"Label: {sp.label}")
    print(f"PseudoPot File: {sp.ppdata.filename}")
    print(f"numatoms:{sp.numatoms}")
    print(f"coords: \n{sp.cryst.T}")
    print()
print(f"numel: {crystal.numel}")
print('-'*40)
print()


alat = 5.107
Axes of real space in cartesian
a(1) = [2.5535 2.5535 2.5535]
a(2) = [-2.5535  2.5535  2.5535]
a(3) = [-2.5535 -2.5535  2.5535]

Axes of real space in alat
a(1) = [0.5 0.5 0.5]
a(2) = [-0.5  0.5  0.5]
a(3) = [-0.5 -0.5  0.5]
----------------------------------------

tpiba = 1.2303084603837058
Axes of reciprocal space in tpiba
b(1) = [1. 0. 1.]
b(2) = [-1.  1.  0.]
b(3) = [ 0. -1.  1.]

Axes of reciprocal space in cart
b(1) = [1.23031 0.      1.23031]
b(2) = [-1.23031  1.23031  0.     ]
b(3) = [ 0.      -1.23031  1.23031]
----------------------------------------

Label: fe
PseudoPot File: Fe_ONCV_PBE-1.2.upf
numatoms:1
coords: 
[[0. 0. 0.]]

numel: 16.0
----------------------------------------



In [5]:
from quantum_masala.core import KPoints, GSpace

grho = GSpace(crystal.recilat, 80)
print(grho.grid_shape)
print(grho.numg)

(18, 18, 18)
2243


In [6]:
from quantum_masala.core import Rho

numspin = 2
rho = Rho(crystal, grho, numspin)

In [7]:
from quantum_masala.core import KPoints

kpts = KPoints.mpgrid(crystal, [8, 8, 8], [False, False, False])
print(kpts.cryst.T, kpts.weights)

[[ 0.     0.     0.   ]
 [ 0.125  0.     0.   ]
 [ 0.25   0.     0.   ]
 [ 0.375  0.     0.   ]
 [ 0.5    0.     0.   ]
 [ 0.25   0.125  0.   ]
 [ 0.375  0.125  0.   ]
 [ 0.5    0.125  0.   ]
 [ 0.5    0.25   0.   ]
 [-0.375  0.25   0.   ]
 [ 0.125  0.125  0.125]
 [ 0.25   0.125  0.125]
 [ 0.375  0.125  0.125]
 [ 0.5    0.125  0.125]
 [ 0.375  0.25   0.125]
 [ 0.5    0.25   0.125]
 [ 0.125  0.375  0.125]
 [-0.375  0.375  0.125]
 [ 0.125  0.5    0.125]
 [ 0.125 -0.375  0.125]
 [ 0.25  -0.375  0.125]
 [ 0.25   0.25   0.25 ]
 [ 0.375  0.25   0.25 ]
 [ 0.5    0.25   0.25 ]
 [ 0.5    0.375  0.25 ]
 [ 0.25  -0.25   0.25 ]
 [ 0.375  0.375  0.375]
 [ 0.5    0.375  0.375]
 [ 0.5    0.5    0.5  ]] [0.00195 0.02344 0.02344 0.02344 0.01172 0.04688 0.09375 0.09375 0.04688
 0.04688 0.01172 0.04688 0.04688 0.02344 0.04688 0.09375 0.01562 0.01562
 0.04688 0.02344 0.04688 0.01172 0.04688 0.02344 0.04688 0.00391 0.01172
 0.02344 0.00195]


In [8]:
kpts = KPoints.from_tpiba(recilat,
                          ([   0.0000000,   0.0000000,   0.0000000],  0.0019531),
                          ([   0.0000000,  -0.1250000,   0.1250000],  0.0234375),
                          ([   0.0000000,  -0.2500000,   0.2500000],  0.0234375),
                          ([   0.0000000,  -0.3750000,   0.3750000],  0.0234375),
                          ([   0.0000000,   0.5000000,  -0.5000000],  0.0117188),
                          ([  -0.1250000,  -0.1250000,   0.2500000],  0.0468750),
                          ([  -0.1250000,  -0.2500000,   0.3750000],  0.0937500),
                          ([  -0.1250000,   0.6250000,  -0.5000000],  0.0937500),
                          ([  -0.2500000,   0.7500000,  -0.5000000],  0.0468750),
                          ([  -0.2500000,   0.6250000,  -0.3750000],  0.0468750),
                          ([   0.0000000,   0.0000000,   0.2500000],  0.0117188),
                          ([   0.0000000,  -0.1250000,   0.3750000],  0.0468750),
                          ([   0.0000000,  -0.2500000,   0.5000000],  0.0468750),
                          ([   0.0000000,   0.6250000,  -0.3750000],  0.0234375),
                          ([  -0.1250000,  -0.1250000,   0.5000000],  0.0468750),
                          ([  -0.1250000,   0.7500000,  -0.3750000],  0.0937500),
                          ([  -0.2500000,   0.2500000,   0.2500000],  0.0156250),
                          ([  -0.2500000,   0.7500000,  -0.2500000],  0.0156250),
                          ([   0.6250000,  -0.6250000,   0.2500000],  0.0468750),
                          ([   0.5000000,  -0.5000000,   0.2500000],  0.0234375),
                          ([   0.5000000,  -0.6250000,   0.3750000],  0.0468750),
                          ([   0.0000000,   0.0000000,   0.5000000],  0.0117188),
                          ([   0.0000000,  -0.1250000,   0.6250000],  0.0468750),
                          ([   0.0000000,   0.7500000,  -0.2500000],  0.0234375),
                          ([  -0.1250000,   0.8750000,  -0.2500000],  0.0468750),
                          ([   0.5000000,  -0.5000000,   0.5000000],  0.0039062),
                          ([   0.0000000,   0.0000000,   0.7500000],  0.0117188),
                          ([   0.0000000,   0.8750000,  -0.1250000],  0.0234375),
                          ([   0.0000000,   0.0000000,  -1.0000000],  0.0019531)
                         )

print(kpts.cryst.T, kpts.weights)

[[ 0.     0.     0.   ]
 [ 0.     0.     0.125]
 [ 0.     0.     0.25 ]
 [ 0.     0.     0.375]
 [ 0.     0.    -0.5  ]
 [ 0.     0.125  0.25 ]
 [ 0.     0.125  0.375]
 [ 0.     0.125 -0.5  ]
 [ 0.     0.25  -0.5  ]
 [ 0.     0.25  -0.375]
 [ 0.125  0.125  0.125]
 [ 0.125  0.125  0.25 ]
 [ 0.125  0.125  0.375]
 [ 0.125  0.125 -0.5  ]
 [ 0.125  0.25   0.375]
 [ 0.125  0.25  -0.5  ]
 [ 0.125  0.375  0.125]
 [ 0.125  0.375 -0.375]
 [ 0.125 -0.5    0.125]
 [ 0.125 -0.375  0.125]
 [ 0.125 -0.375  0.25 ]
 [ 0.25   0.25   0.25 ]
 [ 0.25   0.25   0.375]
 [ 0.25   0.25  -0.5  ]
 [ 0.25   0.375 -0.5  ]
 [ 0.25  -0.25   0.25 ]
 [ 0.375  0.375  0.375]
 [ 0.375  0.375 -0.5  ]
 [-0.5   -0.5   -0.5  ]] [0.00195 0.02344 0.02344 0.02344 0.01172 0.04687 0.09375 0.09375 0.04687
 0.04687 0.01172 0.04687 0.04687 0.02344 0.04687 0.09375 0.01562 0.01562
 0.04687 0.02344 0.04687 0.01172 0.04687 0.02344 0.04687 0.00391 0.01172
 0.02344 0.00195]


In [9]:
from quantum_masala.core import KPointsKgrp, WavefunK, Wfn2Rho

numbnd = 12

WfnK = WavefunK(rho.grho, numspin, numbnd)

kpts_kgrp = KPointsKgrp(kpts)
#print(kpts_kgrp.cryst)
l_wfnk = [WfnK(k_cryst, k_weight, ik) for ik, (k_cryst, k_weight) in enumerate(kpts_kgrp)]
for wfnk in l_wfnk:
    #print(wfnk.gwfc.numgk)
    wfnk.init_random_wfc()

rho_wfn = Wfn2Rho(crystal, WfnK)

In [10]:
wfnk = l_wfnk[0]
print(wfnk.evl.shape)
print(wfnk.occ.shape)
print(wfnk.evc_gk.shape)

(2, 12)
(2, 12)
(2, 12, 321)


In [11]:
from quantum_masala.pw.pot import PPDataLocal, PPDataNonLocal

l_pploc = [PPDataLocal(sp, rho.grho) for sp in crystal.l_species]
l_ppnl = [PPDataNonLocal(sp, WfnK.gspc) for sp in crystal.l_species]

(3, 1) (3, 2243)


In [12]:
mag_start = [0.1, ]

if numspin == 2:
    rho_g = np.zeros((2, grho.numg), dtype="c16")
    for isp, pploc in enumerate(l_pploc):
        rho_g[0] += pploc.rhoatomic_g * (1 + mag_start[isp]) / 2
        rho_g[1] += pploc.rhoatomic_g * (1 - mag_start[isp]) / 2
else:
    rho_g = sum(pploc.rhoatomic_g for pploc in l_pploc).reshape(1, grho.numg)

rho.update(rho_g)

/home/lightpeak008/QuantumMASALA/src/quantum_masala/core/rho.py:164: UserWarning: total charge renormalized from (15.954991497665835+0j) to 16.0
  warn(f"total charge renormalized from {rho_int} to {self.numel}")


In [13]:
from quantum_masala.pw.pot import Hartree, ExchCorr, Ionic
from quantum_masala.pw.pot import compute_ewald_en

vhart = Hartree(rho)
vxc = ExchCorr(rho, 'gga_x_pbe', 'gga_c_pbe')
vion = Ionic(rho, l_pploc)
e_ewald = compute_ewald_en(crystal, rho.grho)

print(f"Ewald Energy: {e_ewald*2} Ry")

Ewald Energy: -182.4248606387626 Ry


In [14]:
from quantum_masala.pw.occ import SmearMod
from quantum_masala.core.constants import eV, E_ryd

occ_mod = SmearMod(WfnK, crystal.numel, "gauss", 0.01*E_ryd) 
print(occ_mod.degauss)

0.005


In [15]:
from quantum_masala.pw.ham import HamK
from quantum_masala.pw.eigsolve.david import david_solve

vbare_g0 = vion.g[0] / np.prod(vion.grho.grid_shape)

def compute_vloc_r():
    vhart.compute()
    vxc.compute()
    return vion.r + vhart.r + vxc.r

vloc_r = compute_vloc_r()
for ik, wfnk in enumerate(l_wfnk):
    #print(ik)
    hamk = HamK(wfnk, vloc_r, l_ppnl)
    for isp in range(wfnk.numspin):
        david_solve(wfnk, hamk, isp, 1E-2, vbare_g0)
    #print(wfnk.evl / eV)

In [16]:
from quantum_masala.pw.mix import GenBroyden

mix_mod = GenBroyden(rho, rho_wfn, 0.7, 8)

In [17]:
e_err = mix_mod.compute_error(rho, rho_wfn)
print(e_err)

46.6689628667685


In [18]:
from quantum_masala.core.constants import E_ryd

diago_thr = 1E-2
conv_thr = 1E-10
scf_converged = False

idxiter = 0
while not scf_converged:
    vloc_r = compute_vloc_r()
    for ik, wfnk in enumerate(l_wfnk):
        #print(ik)
        hamk = HamK(wfnk, vloc_r, l_ppnl)
        for isp in range(wfnk.numspin):
            david_solve(wfnk, hamk, isp, diago_thr, vbare_g0)
            
    l_wfnk = occ_mod.compute(l_wfnk)
    rho_wfn = rho_wfn.update(l_wfnk)
    
    idxiter += 1
    print(f"Iter #{idxiter}")
    e_err = mix_mod.compute_error(rho, rho_wfn)
    print(f"Diago Thr = {diago_thr}, Error = {e_err}")
    
    if e_err < conv_thr * E_ryd:
        scf_converged = True
    if idxiter == 1 and e_err < diago_thr * max(1.0, rho.numel):
        print("Large diago_thr")
        diago_thr = 0.1 * e_err / max(1.0, rho.numel)
    else:
        diago_thr = min(0.1 * e_err / max(1.0, rho.numel), diago_thr)
        diago_thr = max(diago_thr, 1e-13)
        rho = mix_mod.mix(rho, rho_wfn)
    
    print(f"Hart: {vhart.en / E_ryd} Ry")
    print(f"XC: {vxc.en / E_ryd} Ry")

Iter #1
Diago Thr = 0.01, Error = 0.3142553187413723
Hart: (51.91689658472798+3.7265230980548576e-16j) Ry
XC: (-25.312333820651002-1.466693004227097e-17j) Ry
Iter #2
Diago Thr = 0.001964095742133577, Error = 0.12998478554876652
Hart: (46.888074664646595+6.651160776643427e-16j) Ry
XC: (-24.56161956040305-6.955367049811682e-17j) Ry
Iter #3
Diago Thr = 0.0008124049096797908, Error = 0.01702749349178481
Hart: (49.63510281806816+5.309613362370739e-16j) Ry
XC: (-25.011129901137192-2.167657729387797e-17j) Ry
Iter #4
Diago Thr = 0.00010642183432365506, Error = 0.000371379873741049
Hart: (49.01197243814577+4.331423508207104e-16j) Ry
XC: (-24.935019704722922-6.503383597249336e-17j) Ry
Iter #5
Diago Thr = 2.3211242108815564e-06, Error = 4.107253594686747e-05
Hart: (49.08011350847995+2.1429297511763278e-16j) Ry
XC: (-24.947304122973286-1.3677402786478499e-17j) Ry
Iter #6
Diago Thr = 2.567033496679217e-07, Error = 2.2334494239749505e-06
Hart: (49.09859019927653+4.984196022776245e-16j) Ry
XC: (-24.9