In [1]:
import numpy as np

shape_head = (2, 4)
shape_tail = (10, )

dat = np.random.rand(*(*shape_head, *shape_tail))
dat_bak= dat.copy()

print(f"Shape: {shape_head} + {shape_tail}")

mask = np.random.rand(*shape_tail) > 0.5
idx = np.nonzero(mask)

print("Mask")
print(mask)
print(f"Count: {np.sum(mask)}, Indices: {idx[0]}")

Shape: (2, 4) + (10,)
Mask
[ True  True False  True False  True  True  True  True False]
Count: 7, Indices: [0 1 3 5 6 7 8]


In [2]:
# Accessing
sl = (slice(None), ) * len(shape_head) + (mask, )
print(dat[sl].shape, dat[sl].base.shape, dat[sl].base is dat)

# Writing
dat[sl] = 0
print(np.all(dat == dat_bak))
print(dat)

# Restoring array
dat[:] = dat_bak

(2, 4, 7) (7, 2, 4) False
False
[[[0.         0.         0.05083801 0.         0.59172221 0.
   0.         0.         0.         0.41339882]
  [0.         0.         0.25706593 0.         0.53193681 0.
   0.         0.         0.         0.0061467 ]
  [0.         0.         0.42510126 0.         0.7048283  0.
   0.         0.         0.         0.81593823]
  [0.         0.         0.06278819 0.         0.21090457 0.
   0.         0.         0.         0.63549142]]

 [[0.         0.         0.12261577 0.         0.91980184 0.
   0.         0.         0.         0.88885465]
  [0.         0.         0.32996032 0.         0.90220704 0.
   0.         0.         0.         0.40586513]
  [0.         0.         0.83317625 0.         0.02073766 0.
   0.         0.         0.         0.54659591]
  [0.         0.         0.92098642 0.         0.28628369 0.
   0.         0.         0.         0.326205  ]]]


In [3]:
# Accessing
sl = (slice(None), ) * len(shape_head) + idx
print(dat[sl].shape, dat[sl].base.shape, dat[sl].base is dat)

# Writing
dat[sl] = 0
print(np.all(dat == dat_bak))
print(dat)

# Restoring array
dat[:] = dat_bak

(2, 4, 7) (7, 2, 4) False
False
[[[0.         0.         0.05083801 0.         0.59172221 0.
   0.         0.         0.         0.41339882]
  [0.         0.         0.25706593 0.         0.53193681 0.
   0.         0.         0.         0.0061467 ]
  [0.         0.         0.42510126 0.         0.7048283  0.
   0.         0.         0.         0.81593823]
  [0.         0.         0.06278819 0.         0.21090457 0.
   0.         0.         0.         0.63549142]]

 [[0.         0.         0.12261577 0.         0.91980184 0.
   0.         0.         0.         0.88885465]
  [0.         0.         0.32996032 0.         0.90220704 0.
   0.         0.         0.         0.40586513]
  [0.         0.         0.83317625 0.         0.02073766 0.
   0.         0.         0.         0.54659591]
  [0.         0.         0.92098642 0.         0.28628369 0.
   0.         0.         0.         0.326205  ]]]


In [4]:
import numpy as np

shape_head = (2, 4)
shape_tail = (3, 5)

dat = np.random.rand(*(*shape_head, *shape_tail))
dat_bak= dat.copy()

print(f"Shape: {shape_head} + {shape_tail}")

mask = np.random.rand(*shape_tail) > 0.5
idx = np.nonzero(mask)

print("Mask")
print(mask)
print(f"Count: {np.sum(mask)}, Indices:\n{np.array(idx)}")

Shape: (2, 4) + (3, 5)
Mask
[[False  True  True False  True]
 [False  True  True False  True]
 [ True  True False False False]]
Count: 8, Indices:
[[0 0 0 1 1 1 2 2]
 [1 2 4 1 2 4 0 1]]


In [5]:
# Accessing
sl = (slice(None), ) * len(shape_head) + (mask, )
print(dat[sl].shape, dat[sl].base.shape, dat[sl].base is dat)

# Writing
dat[sl] = 0
print(np.all(dat == dat_bak))
print(dat)

# Restoring array
dat[:] = dat_bak

(2, 4, 8) (8, 2, 4) False
False
[[[[0.37862546 0.         0.         0.95049346 0.        ]
   [0.44748575 0.         0.         0.2604028  0.        ]
   [0.         0.         0.9130436  0.37846377 0.38842555]]

  [[0.90823889 0.         0.         0.00620796 0.        ]
   [0.8545222  0.         0.         0.94112365 0.        ]
   [0.         0.         0.89834424 0.60395757 0.97621934]]

  [[0.9459852  0.         0.         0.89419759 0.        ]
   [0.24887895 0.         0.         0.26558549 0.        ]
   [0.         0.         0.73434074 0.09681712 0.9126964 ]]

  [[0.15504323 0.         0.         0.79921166 0.        ]
   [0.86846969 0.         0.         0.01136617 0.        ]
   [0.         0.         0.07326025 0.99345128 0.24734726]]]


 [[[0.95528074 0.         0.         0.02761119 0.        ]
   [0.87445408 0.         0.         0.12240327 0.        ]
   [0.         0.         0.5818263  0.74234262 0.59950214]]

  [[0.0170425  0.         0.         0.50250744 0.      

In [6]:
# Accessing
sl = (slice(None), ) * len(shape_head) + idx
print(dat[sl].shape, dat[sl].base.shape, dat[sl].base is dat)

# Writing
dat[sl] = 0
print(np.all(dat == dat_bak))
print(dat)

# Restoring array
dat[:] = dat_bak

(2, 4, 8) (8, 2, 4) False
False
[[[[0.37862546 0.         0.         0.95049346 0.        ]
   [0.44748575 0.         0.         0.2604028  0.        ]
   [0.         0.         0.9130436  0.37846377 0.38842555]]

  [[0.90823889 0.         0.         0.00620796 0.        ]
   [0.8545222  0.         0.         0.94112365 0.        ]
   [0.         0.         0.89834424 0.60395757 0.97621934]]

  [[0.9459852  0.         0.         0.89419759 0.        ]
   [0.24887895 0.         0.         0.26558549 0.        ]
   [0.         0.         0.73434074 0.09681712 0.9126964 ]]

  [[0.15504323 0.         0.         0.79921166 0.        ]
   [0.86846969 0.         0.         0.01136617 0.        ]
   [0.         0.         0.07326025 0.99345128 0.24734726]]]


 [[[0.95528074 0.         0.         0.02761119 0.        ]
   [0.87445408 0.         0.         0.12240327 0.        ]
   [0.         0.         0.5818263  0.74234262 0.59950214]]

  [[0.0170425  0.         0.         0.50250744 0.      

In [7]:
class Test:
    def __init__(self):
        self.num = 10
        
    def __eq__(self, other):
        if self.num == other.num:
            return True
        return False

In [11]:
t = Test()
hasattr(t, '__add__')

False

In [5]:
import numpy as np

s1 = (10, 10)
s2 = (5, 10)

A = np.random.rand(*s1) + 1j * np.random.rand(*s1)
B = np.random.rand(*s2) + 1j * np.random.rand(*s2)

print(A.dtype, B.dtype)

complex128 complex128


In [6]:
from numpy.array_api import vecdot
C = vecdot(A.real, B.real, axis=1)

AttributeError: 'numpy.ndarray' object has no attribute '_array'