In [4]:
import numpy as np
from qtmpy.constants import ANGSTROM

# Defining a BCC Lattice
alat = 5.1 * ANGSTROM  # Lattice parameter 'a'
# Lattice vectors
latvec_alat = 0.5 * np.array([
    [ 1,  1,  1],
    [-1,  1,  1],
    [-1, -1,  1]
])

In [17]:
from qtmpy.lattice import RealLattice, ReciLattice

# Creating RealLattice instance representing FCC lattice
reallat = RealLattice.from_alat(alat, *latvec_alat)
# Creating ReciLattice insance from reallat
recilat = ReciLattice.from_reallat(reallat)

# Printing axes
print(reallat.alat, reallat.axes_alat)
print(recilat.tpiba, recilat.axes_tpiba)

9.637603235591428 ([0.5, 0.5, 0.5], [-0.5, 0.5, 0.5], [-0.5, -0.5, 0.5])
0.6519447993019614 ([0.9999999999999998, 0.0, 0.9999999999999998], [-0.9999999999999998, 0.9999999999999998, 0.0], [0.0, -0.9999999999999998, 0.9999999999999998])


In [16]:
vec_cryst = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [1, 1, 0],
    [0, 1, 1]
])
print(vec_cryst.shape)
vec_cart = reallat.cryst2cart(vec_cryst, axis=1)
print(vec_cart)
vec_alat = reallat.cryst2alat(vec_cryst, axis=1)
print(vec_alat)
len_alat = reallat.norm(vec_cryst.T, coords='cryst')
print(len_alat / reallat.alat)

(4, 3)
[[ 4.81880162  4.81880162  4.81880162]
 [-4.81880162  4.81880162  4.81880162]
 [ 0.          9.63760324  9.63760324]
 [-9.63760324  0.          9.63760324]]
[[ 0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.   1.   1. ]
 [-1.   0.   1. ]]
[0.8660254  0.8660254  1.41421356 1.41421356]


In [18]:
import numpy as np

from qtmpy.lattice import RealLattice, ReciLattice
from qtmpy.constants import ANGSTROM

# Defining a BCC Lattice
alat = 5.1 * ANGSTROM  # Lattice parameter 'a'
# Lattice vectors
latvec_alat = 0.5 * np.array([
    [ 1,  1,  1],
    [-1,  1,  1],
    [-1, -1,  1]
])

# Creating RealLattice instance representing FCC lattice
reallat = RealLattice.from_alat(alat, *latvec_alat)
# Creating ReciLattice insance from reallat
recilat = ReciLattice.from_reallat(reallat)

# Printing axes
print(reallat.alat, reallat.axes_alat)
## 9.637603235591428 ([0.5, 0.5, 0.5], [-0.5, 0.5, 0.5], [-0.5, -0.5, 0.5])

print(recilat.tpiba, recilat.axes_tpiba)
## 0.6519447993019614 ([1.0, 0.0, 1.0], [-1.0, 1.0, 0.0], [0.0, -1.0, 1.0])

# Input array of vectors in crystal coordinates
vec_cryst = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [1, 1, 0],
    [0, 1, 1]
])

# Coordinate Transforms
vec_cart = reallat.cryst2cart(vec_cryst, axis=1)
print(vec_cart)
## [[ 4.81880162  4.81880162  4.81880162]
##  [-4.81880162  4.81880162  4.81880162]
##  [ 0.          9.63760324  9.63760324]
##  [-9.63760324  0.          9.63760324]]

vec_alat = reallat.cryst2alat(vec_cryst, axis=1)
print(vec_alat)
## [[ 0.5  0.5  0.5]
##  [-0.5  0.5  0.5]
##  [ 0.   1.   1. ]
##  [-1.   0.   1. ]]

# NOTE: As per convention, the first dimension of vector lists
# must correspond to the components, resulting in a shape of
# form (3, ...)
len_alat = reallat.norm(vec_cryst.T, coords='cryst')
print(len_alat / reallat.alat)
## [0.8660254  0.8660254  1.41421356 1.41421356]

9.637603235591428 ([0.5, 0.5, 0.5], [-0.5, 0.5, 0.5], [-0.5, -0.5, 0.5])
0.6519447993019614 ([0.9999999999999998, 0.0, 0.9999999999999998], [-0.9999999999999998, 0.9999999999999998, 0.0], [0.0, -0.9999999999999998, 0.9999999999999998])
[[ 4.81880162  4.81880162  4.81880162]
 [-4.81880162  4.81880162  4.81880162]
 [ 0.          9.63760324  9.63760324]
 [-9.63760324  0.          9.63760324]]
[[ 0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.   1.   1. ]
 [-1.   0.   1. ]]
[0.8660254  0.8660254  1.41421356 1.41421356]


In [24]:
from qtmpy.gspace.gspc import GSpace
from qtmpy.constants import RYDBERG

# Creating a GSpace instance with KE cutoff 40 Ry
gspc = GSpace(recilat, 40 * RYDBERG)
print(gspc.grid_shape, gspc.size)
## (18, 18, 18) 1961

# Printing the G-vectors of gspc
with np.printoptions(edgeitems=5, formatter={
    'float': lambda num: f'{num:5.1f}',
    'int': lambda num: f'{float(num):5.1f}',
}):
    for i in range(3):
        print(f'G_{i+1}: ', gspc.g_cryst[i])
    print(f'G^2: ', gspc.g_norm2)
## G_1:  [  0.0   0.0   0.0   0.0   0.0 ...  -1.0  -1.0  -1.0  -1.0  -1.0]
## G_2:  [  0.0   0.0   0.0   0.0   0.0 ...  -1.0  -1.0  -1.0  -1.0  -1.0]
## G_3:  [  0.0   1.0   2.0   3.0   4.0 ...  -5.0  -4.0  -3.0  -2.0  -1.0]
## G^2:  [  0.0   0.9   3.4   7.7  13.6 ...  22.1  14.5   8.5   4.3   1.7]

# Creating a array representing a scalar field
sfield_r = gspc.create_buffer_r(1)
sfield_r[:] = np.random.rand(*gspc.grid_shape) \
    + np.random.rand(*gspc.grid_shape)

# Transforming to G-Space
sfield_g = gspc.r2g(sfield_r)

# The above is equivalent to 3D FFT followed by taking elements in field
print(np.allclose(sfield_g, np.fft.fftn(sfield_r).take(gspc.idxgrid)))
## True

(18, 18, 18) 1961
G_1:  [  0.0   0.0   0.0   0.0   0.0 ...  -1.0  -1.0  -1.0  -1.0  -1.0]
G_2:  [  0.0   0.0   0.0   0.0   0.0 ...  -1.0  -1.0  -1.0  -1.0  -1.0]
G_3:  [  0.0   1.0   2.0   3.0   4.0 ...  -5.0  -4.0  -3.0  -2.0  -1.0]
G^2:  [  0.0   0.9   3.4   7.7  13.6 ...  22.1  14.5   8.5   4.3   1.7]
