In [1]:
import numpy as np

In [2]:
from abc import ABC, abstractmethod

class A:
    
    _attr = 10
    
    def __init__(self):
        self.val = self._attr * 10

In [3]:
class B(A):
    
    def __init__(self, newattr):
        self._attr = newattr
        super().__init__()

In [5]:
a = A()
print(A._attr, a._attr, a.val)
b = B(-20)
print(B._attr, b._attr, b.val)

10 10 100
10 -20 -200


In [54]:
class Test:
    
    size = 10
    
    def __init__(self, shape):
        if isinstance(shape, int):
            shape = (shape, )
        self.shape = (*shape, self.size)
        self.arr = np.arange(
            np.prod(self.shape)
        ).reshape(self.shape)
    
    @property
    def ndim(self):
        return self.arr.ndim
    
    @property
    def rank(self):
        return self.ndim - 1
    
    def __getitem__(self, key):
        print('key is', key)
        view = self.arr.reshape((-1, self.size))
        view = view[:, key]
        return view.reshape((*self.shape[:-1], -1))
    
    def __setitem__(self, key, val):
        print('key is', key)
        view = self.arr.reshape((-1, self.size))
        view[:, key] = val

In [55]:
t = Test((2, 5))
print(t.arr.shape)
print(t.arr)

a = t[([0,2,3,4],[1,2,3,3])]
print(a.shape)
print(a)
t[mask] = -1
print(t.arr)

(2, 5, 10)
[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]
key is ([0, 2, 3, 4], [1, 2, 3, 3])
(2, 5, 8)
[[[ 0  2  3  4  1  2  3  3]
  [10 12 13 14 11 12 13 13]
  [20 22 23 24 21 22 23 23]
  [30 32 33 34 31 32 33 33]
  [40 42 43 44 41 42 43 43]]

 [[50 52 53 54 51 52 53 53]
  [60 62 63 64 61 62 63 63]
  [70 72 73 74 71 72 73 73]
  [80 82 83 84 81 82 83 83]
  [90 92 93 94 91 92 93 93]]]
key is [ True False False  True False  True False False False False]
[[[-1  1  2 -1  4 -1  6  7  8  9]
  [-1 11 12 -1 14 -1 16 17 18 19]
  [-1 21 22 -1 24 -1 26 27 28 29]
  [-1 31 32 -1 34 -1 36 37 38 39]
  [-1 41 42 -1 44 -1 46 47 48 49]]

 [[-1 51 52 -1 54 -1 56 57 58 59]
  [-1 61 62 -1 64 -1 66 67 68 69]
  [-1 

In [43]:
t = Test((2, 5))
print(t.arr.shape)
print(t.arr)

mask = np.zeros(t.size, dtype='bool')
mask[[0,3,5]] = True

a = t[mask]
print(a.shape)
print(a)
t[mask] = -1
print(t.arr)

(2, 5, 10)
[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]
key is [ True False False  True False  True False False False False]
(2, 5, 3)
[[[ 0  3  5]
  [10 13 15]
  [20 23 25]
  [30 33 35]
  [40 43 45]]

 [[50 53 55]
  [60 63 65]
  [70 73 75]
  [80 83 85]
  [90 93 95]]]
key is [ True False False  True False  True False False False False]
[[[-1  1  2 -1  4 -1  6  7  8  9]
  [-1 11 12 -1 14 -1 16 17 18 19]
  [-1 21 22 -1 24 -1 26 27 28 29]
  [-1 31 32 -1 34 -1 36 37 38 39]
  [-1 41 42 -1 44 -1 46 47 48 49]]

 [[-1 51 52 -1 54 -1 56 57 58 59]
  [-1 61 62 -1 64 -1 66 67 68 69]
  [-1 71 72 -1 74 -1 76 77 78 79]
  [-1 81 82 -1 84 -1 86 87 88 89]
  [-1 91 92 -1 94 -1 96 97 98 99]]]


In [2]:
import numpy as np

a = np.arange(10).reshape(2,5)
b = a[..., np.newaxis]
print(a.shape, b.shape)
print(a.base is b.base)

c = np.asarray(10)
d = c[..., np.newaxis]
print(c, d.shape)

(2, 5) (2, 5, 1)
True
10 (1,)
